# Generated by Django 3.1 on 2024-09-24 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargos',
            fields=[
                ('codigo_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('identificacion_cliente', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('codigo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mascotas',
            fields=[
                ('codigo_mascotas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=50, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('alimentacion', models.CharField(max_length=255, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('genero', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('identificacion_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='citas.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('codigo_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('codigo_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='citas.cargos')),
            ],
        ),
        migrations.CreateModel(
            name='citas',
            fields=[
                ('codigo_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('codigo_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.empleados')),
                ('codigo_mascotas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.mascotas')),
                ('codigo_servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.servicios')),
            ],
        ),
    ]
