# Generated by Django 3.1 on 2024-09-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos',
            name='codigo_cargo',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citas',
            name='codigo_cita',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
