# Generated by Django 3.1 on 2024-09-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20240924_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos',
            name='codigo_cargo',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='citas',
            name='codigo_cita',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='codigo_empleado',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='codigo_mascotas',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='codigo_servicio',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
